#!/bin/sh


function usage()
{
	echo "USAGE: ./code-stats [ROOT_IRATI_DIR]"
		exit 1
}

function stats()
{
	name=$1
	shift
	count=$(find $@ -type f -and \( -name "*.c" -or -name "*.h" -or -name "*.cc" -or -name "*.hpp" \)| grep -v "tclap" | grep -v "jsoncpp" | grep -v "\.mod\.c" | xargs wc -l | tail -n 1 | awk '{print $1}')
	printf "%-15s %10s lines\n" $name $count
}

if [ -n "$1" ]; then
	[ -d "$1" ] || usage
	cd "$1"
fi

[ -d "librina" ] || usage

stats kernel linux/net/rina
stats librina librina/include librina/src
stats rinad rinad/src
stats rina-tools rina-tools/src
stats total linux/net/rina librina/include librina/src rinad/src rina-tools/src

echo -e "\nCode editing statistics between IRATI 1.0.0 and current pristine development branch"
git diff --stat v1.0.0 pristine-1.5 librina/ rinad/ rina-tools/src/ linux/net/rina plugins/ | tail -n 1
