#!/bin/sh
# -*- sh -*-

#
# bootstrap
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=bootstrap

DIRS="librina"

echo "${ME}: Bootstrapping $DIRS"

for i in $DIRS ; do
    (cd $i && echo "${ME}: Bootstrapping directory $PWD" && ./bootstrap) || {
        echo "${ME}: Cannot bootstrap directory $PWD"
        exit 1
    }
done

echo "${ME}: Bootstrap completed successfully"
