#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#

#
# Do not touch under this line
#

ME=compile-kernel

echo "$ME: Compiling kernel modules"
(cd kernel && ./configure && make) || {
    echo "$ME: Cannot complete kernel compilation"
    exit 1
}
