#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=compile-user

PREFIX=`echo "$1"|sed -e "s,\/$,,"`
(cd librina && make) && (cd rinad && make) && (cd rina-tools && make) || {
    echo "$ME: Cannot complete compilation phase"
    exit 1
}
