#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#
PREFIX=`echo "$1"|sed -e "s,\/$,,"`

#
# Do not touch under this line
#

ME=compile-user

. ./.env || {
    echo "$ME: Cannot load environment"
    exit 1
}

#
# Do not touch under this line
#
(cd $BUILDDIR/librina    && make) && \
(cd $BUILDDIR/rinad      && make) && \
(cd $BUILDDIR/rina-tools && make) || {
    echo "$ME: Cannot complete compilation phase"
    exit 1
}
