#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=uninstall

echo "$ME: Starting phase rina-tools"
(cd rinad && make distclean) || {
    echo "$ME: Cannot install rina-tools phase"
    exit 1
}

echo "$ME: Starting phase rinad"
(cd rinad && make distclean) || {
    echo "$ME: Cannot install rinad phase"
    exit 1
}

echo "$ME: Starting phase librina"
(cd librina && make distclean) || {
    echo "$ME: Cannot complete librina phase"
    exit 1
}

