#!/bin/sh
# -*- sh -*-

#
# install-from-scratch
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=install-from-scratch

echo "$ME: Starting phase librina"
(cd librina && ./bootstrap && ./configure --enable-java-bindings --prefix=$1 && make install) || {
    echo "$ME: Cannot complete librina phase"
    exit 1
}

echo "$ME: Starting phase rinad"
(cd rinad && ./bootstrap && PKG_CONFIG_PATH=$1/lib/pkgconfig ./configure --prefix=$1 && make install) || {
    echo "$ME: Cannot install rinad phase"
    exit 1
}

echo "$ME: Starting phase rina-tools"
(cd rinad && ./bootstrap && PKG_CONFIG_PATH=$1/lib/pkgconfig ./configure --prefix=$1 && make install) || {
    echo "$ME: Cannot install rina-tools phase"
    exit 1
}
