#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=install-kernel-precompiled

PREFIX=`echo "$1"|sed -e "s,\/$,,"`

echo "$ME: Prefix is \`$PREFIX'"
if test -n "$PREFIX" ; then
    mkdir -p $PREFIX || {
        echo "$ME: Cannot create directory \`$PREFIX'"
    }
fi

#
# FIXME: we should definitely do a VPATH build ...
#

(cd linux && make headers_install_all INSTALL_HDR_PATH=$PREFIX/usr/include/linux) || {
    echo "$ME: Cannot install kernel headers"
    exit 1
}
(cd linux && INSTALL_PATH=$PREFIX/boot INSTALL_MOD_PATH=$PREFIX make modules_install install) || {
    echo "$ME: Cannot complete kernel installation"
    exit 1
}
