#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#

#
# Do not change under this line
#

ME=install-kernel

echo "$ME: Installing kernel modules"
(cd kernel && make install && depmod -a) || {
    echo "$ME: Cannot install kernel modules"
    exit 1
}
