#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=install-user-from-scratch

PREFIX=`echo "$1"|sed -e "s,\/$,,"`

echo "$ME: Prefix is \`$PREFIX'"
if test -n "$PREFIX" ; then
    mkdir -p $PREFIX || {
        echo "$ME: Cannot create directory \`$PREFIX'"
    }
fi

#
# FIXME: we should definitely do a VPATH build ...
#

echo "$ME: Starting librina phase"
(cd librina && ./bootstrap && ./configure --enable-java-bindings --with-sysheaders=`pwd`/../linux/usr/include --prefix=$PREFIX && make clean install installcheck) || {
    echo "$ME: Cannot complete librina phase"
    exit 1
}

echo "$ME: Starting rinad phase"
(cd rinad && ./bootstrap && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib ./configure --prefix=$PREFIX && make clean install installcheck) || {
    echo "$ME: Cannot complete rinad phase"
    exit 1
}

echo "$ME: Starting rina-tools phase"
(cd rina-tools && ./bootstrap && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib ./configure --prefix=$PREFIX --enable-java-support && make clean all install installcheck) || {
    echo "$ME: Cannot complete rina-tools phase"
    exit 1
}
