#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=install-user-precompiled

#
# FIXME: we should definitely do a VPATH build ...
#

echo "$ME: Starting librina phase"
(cd librina && make install installcheck) || {
    echo "$ME: Cannot complete librina phase"
    exit 1
}

echo "$ME: Starting rinad phase"
(cd rinad && make install installcheck) || {
    echo "$ME: Cannot complete rinad phase"
    exit 1
}

echo "$ME: Starting rina-tools phase"
(cd rina-tools && make install installcheck) || {
    echo "$ME: Cannot complete rina-tools phase"
    exit 1
}
