#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#
PREFIX=`echo "$1"|sed -e "s,\/$,,"`
SRCDIR=`pwd`
FLAGS="--enable-debug"

#
# Do not touch under this line
#

ME=install-user-from-scratch

. ./.env || {
    echo "$ME: Cannot load environment"
    exit 1
}

echo "$ME: Installation directory will be \`$PREFIX'"
if test -n "$PREFIX" ; then
    mkdir -p $PREFIX || {
        echo "$ME: Cannot create directory \`$PREFIX'"
    }
fi

echo "$ME: Build directory will be \`$BUILDDIR'"
if test -n "$BUILDDIR" ; then
    mkdir -p $BUILDDIR || {
        echo "$ME: Cannot create directory \`$BUILDDIR'"
    }
fi

echo "$ME: Java directory will be \`$BUILDDIR/java'"
if test -n "$BUILDDIR/java" ; then
    mkdir -p $BUILDDIR/java || {
        echo "$ME: Cannot create directory \`$BUILDDIR/java'"
    }
fi

echo "$ME: Starting librina phase"
(cd librina && ./bootstrap) || {
    echo "$ME: Cannot bootstrap"
    exit 1
}
(mkdir -p $BUILDDIR/librina && cd $BUILDDIR/librina && $SRCDIR/librina/configure --enable-java-bindings $FLAGS --with-sysheaders=$SRCDIR/linux/usr/include --prefix=$PREFIX && make $MAKEFLAGS clean install installcheck) || {
    echo "$ME: Cannot complete librina phase"
    exit 1
}

echo "$ME: Starting rinad phase"
(cd rinad && ./bootstrap) || {
    echo "$ME: Cannot bootstrap"
    exit 1
}
(mkdir -p $BUILDDIR/rinad && cd $BUILDDIR/rinad && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH $SRCDIR/rinad/configure --prefix=$PREFIX --enable-java-bindings $FLAGS && make $MAKEFLAGS clean install installcheck) || {
    echo "$ME: Cannot complete rinad phase"
    exit 1
}

echo "$ME: Starting rina-tools phase"
(cd rina-tools && ./bootstrap) || {
    echo "$ME: Cannot bootstrap"
    exit 1
}
(mkdir -p $BUILDDIR/rina-tools && cd $BUILDDIR/rina-tools && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH $SRCDIR/rina-tools/configure $FLAGS --prefix=$PREFIX && make $MAKEFLAGS clean all install installcheck) || {
    echo "$ME: Cannot complete rina-tools phase"
    exit 1
}
