#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#

#
# Do not change under this line
#

ME=install-from-scratch

. ./.env || {
    echo "$ME: Cannot load environment"
    exit 1
}

./compile-kernel && ./install-kernel $@ || {
    echo "$ME: Cannot compile or install the kernel from scratch"
    exit 1
}

./install-user-from-scratch $@ || {
    echo "$ME: Cannot install the user parts from scratch"
    exit 1
}
