#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#

#
# Do not touch under this line
#

ME=install-user-precompiled

. ./.env || {
    echo "$ME: Cannot load environment"
    exit 1
}

echo "$ME: Starting librina phase"
(cd $BUILDDIR/librina && make install installcheck) || {
    echo "$ME: Cannot complete librina phase"
    exit 1
}

echo "$ME: Starting rinad phase"
(cd $BUILDDIR/rinad && make install installcheck) || {
    echo "$ME: Cannot complete rinad phase"
    exit 1
}

echo "$ME: Starting rina-tools phase"
(cd $BUILDDIR/rina-tools && make install installcheck) || {
    echo "$ME: Cannot complete rina-tools phase"
    exit 1
}
