#!/bin/sh
# -*- sh -*-

#
# Written by: Eduard Grasa <eduard DOT grasa AT i2CAT DOT net>
#

modprobe rina-irati-core irati_verbosity=7
modprobe rina-default-plugin
modprobe normal-ipcp
modprobe shim-eth-vlan
modprobe shim-tcp-udp

#Up RINA IP hub virtual device
ifconfig rina_ip up
