#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#

#
# Do not touch under this line
#

ME=uninstall-user

. ./.env || {
    echo "$ME: Cannot load environment"
    exit 1
}

echo "$ME: Uninstalling rina-tools"
(cd $BUILDDIR/rina-tools && make uninstall) || {
    echo "$ME: Cannot uninstall rina-tools"
    exit 1
}

echo "$ME: Uninstalling rinad"
(cd $BUILDDIR/rinad && make uninstall) || {
    echo "$ME: Cannot uninstall rinad"
    exit 1
}

echo "$ME: Uninstalling librina"
(cd $BUILDDIR/librina && make uninstall) || {
    echo "$ME: Cannot uninstall librina"
    exit 1
}
