#
# Makefile for the RINA Data Structures (RDS) layer
#
# Written by Francesco Salvestrini <f.salvestrini@nextworks.it>
#

ccflags-y += -I$(srctree)/net/rina

obj-$(CONFIG_RINA) +=				\
	 rmem.o rmap.o rwq.o rqueue.o rbmp.o
