#line 2 "radius_dict.c"

#line 4 "radius_dict.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer Radius_create_buffer
#define yy_delete_buffer Radius_delete_buffer
#define yy_flex_debug Radius_flex_debug
#define yy_init_buffer Radius_init_buffer
#define yy_flush_buffer Radius_flush_buffer
#define yy_load_buffer_state Radius_load_buffer_state
#define yy_switch_to_buffer Radius_switch_to_buffer
#define yyin Radiusin
#define yyleng Radiusleng
#define yylex Radiuslex
#define yylineno Radiuslineno
#define yyout Radiusout
#define yyrestart Radiusrestart
#define yytext Radiustext
#define yywrap Radiuswrap
#define yyalloc Radiusalloc
#define yyrealloc Radiusrealloc
#define yyfree Radiusfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Radiusrestart(Radiusin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int Radiusleng;

extern FILE *Radiusin, *Radiusout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Radiustext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Radiustext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Radiusrestart()), so that the user can continue scanning by
	 * just pointing Radiusin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when Radiustext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int Radiusleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow Radiuswrap()'s to do buffer switches
 * instead of setting up a fresh Radiusin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void Radiusrestart (FILE *input_file  );
void Radius_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Radius_create_buffer (FILE *file,int size  );
void Radius_delete_buffer (YY_BUFFER_STATE b  );
void Radius_flush_buffer (YY_BUFFER_STATE b  );
void Radiuspush_buffer_state (YY_BUFFER_STATE new_buffer  );
void Radiuspop_buffer_state (void );

static void Radiusensure_buffer_stack (void );
static void Radius_load_buffer_state (void );
static void Radius_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER Radius_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE Radius_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE Radius_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE Radius_scan_bytes (yyconst char *bytes,int len  );

void *Radiusalloc (yy_size_t  );
void *Radiusrealloc (void *,yy_size_t  );
void Radiusfree (void *  );

#define yy_new_buffer Radius_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Radiusensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Radius_create_buffer(Radiusin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Radiusensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Radius_create_buffer(Radiusin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *Radiusin = (FILE *) 0, *Radiusout = (FILE *) 0;

typedef int yy_state_type;

extern int Radiuslineno;

int Radiuslineno = 1;

extern char *Radiustext;
#define yytext_ptr Radiustext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Radiustext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	Radiusleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[298] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       13,   13,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   15,   15,   61,   60,   59,    2,
        1,   60,    1,    1,   60,   60,   16,    1,   17,   17,
       28,    1,   29,   29,   47,    1,    1,   47,   47,   47,
       47,    1,   47,   47,   47,   52,   51,    1,   51,   51,
       53,   54,    1,   55,   55,    2,    1,   56,   56,   58,
        2,    1,   60,    2,    1,   60,   12,    1,   13,    2,

        1,   27,   60,   23,   20,   24,   60,   25,   60,   26,
       14,    1,   15,    2,    1,    2,    0,    0,    0,    0,
        0,    0,   16,   17,    0,   28,   29,    0,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   51,   50,   51,   51,   54,   55,    2,   56,
        0,   58,    2,    0,    0,    2,    2,    3,   12,   13,
        2,    0,   21,   22,   14,   15,    2,    0,    0,    0,
        0,    0,    0,   18,   30,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   46,
       50,   51,   51,   57,    2,    0,    0,    0,    0,    0,

        0,    0,   47,   42,   47,   38,   47,   41,   47,   47,
       47,   47,   47,   47,   47,   47,   51,   51,    0,    0,
        0,    0,    0,    0,    6,    0,   47,   47,   40,   47,
       47,   47,   47,   47,   47,   43,   47,   47,   51,   51,
        0,    0,    0,    0,    0,    0,    4,   47,   47,   47,
       34,   47,   47,   37,   33,   44,   32,   51,   51,    0,
        0,    0,    0,    0,   11,    0,   39,   47,   31,   47,
       47,   51,   48,   19,    7,    0,    0,    0,    0,   45,
       35,   47,   50,   48,    5,   10,    0,    0,   47,   49,
        0,    9,   36,   49,    0,    8,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   11,   11,
       12,   13,   14,   15,   14,   14,   14,   16,    1,    1,
       17,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   27,   40,   41,   27,
        1,    1,    1,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   27,   28,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   27,   63,
       64,   27,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    5,    6,    7,
        7,    7,    7,    7,    7,    1,    8,    7,    7,    7,
        7,    7,    7,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    7,    7,    7,    7,    7,    7,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[332] =
    {   0,
        0,   52,  104,    0,  166,  220,  270,    0,  332,  386,
        0,   10,  440,    0,  504,  558,   23,   36,  612,  666,
      719,  772,   47,   62,  825,  878,  930,  985, 1042, 1096,
     1148, 1200,   76,  102,  126,  149,  190,  244,  284,  309,
      176,  230, 1254, 1308, 1360, 1412,  165, 1688, 1688,    0,
     1688,   14,    4,   20,   38,  282,    0,    0,  330,  201,
        0,    0,  343,  255,    0,   34,   57,   79,   67,   82,
      377,    0,   73,  372,  101, 1688,  132,  129,  262,   84,
     1688,    0,    0,    0,    0,    3,    0,  528,  354,    0,
       98,    0,   97,  121,  123,  274,    0,    0,    0,    0,

        0, 1688,  144, 1688, 1688, 1688,  134, 1688,   83, 1688,
        0,    0,    0,    0,    0,    0,  176,  171,  149,  160,
      224,  247,    0,  367,    0,    0,  504,    0,    0,  166,
      266,  277,  302,  202,  209,  334,  356,  364,  379,  222,
      377,  374,   80,    0,  507,  494,    0,    0,    5,  582,
        0,    0,   92,  382,  515,  500,  550,  516,    0,    0,
        0,  520, 1688, 1688,    0,    0,    0,  241,  530,  251,
       77,  560,  306,    0,    0,  568,  325,  526,  578,  587,
      590,  597,  602,   67,  572,  602,  592,  604,  606,    0,
        0,  628,  620,    0,  604,  612,  623,  625,  623,  641,

      651,  647,  663,    0,  656,    0,  654,    0,  666,  670,
      674,  677,  659,  667,  678,  674,  691,  676,  696,  688,
      710,   59,  704,  712, 1688,  706,  707,   56,    0,  721,
      709,  724,  711,  720,  722,    0,  731,  729,  749,  743,
      735,  758,  745,  748,  745,  758, 1688,  753,  767,  761,
        0,  776,  776,    0,    0,    0,    0,  797,  796,   28,
      789,  765,  780,  799, 1688,  809,    0,  802,    0,  802,
      815,   15,  256, 1688, 1688,  817,  803,  816,  816,    0,
        0,  823,  299, 1688, 1688, 1688,  829,  826,  822,   24,
      834, 1688,    0,    0,  832, 1688, 1688, 1466, 1474, 1482,

     1490, 1498, 1506, 1514, 1522, 1530, 1538, 1546, 1554, 1562,
     1567, 1571, 1575, 1579, 1584, 1591, 1599, 1607, 1615, 1623,
     1631, 1636, 1643, 1651, 1656, 1663, 1671,   20,   10, 1679,
        2
    } ;

static yyconst flex_int16_t yy_def[332] =
    {   0,
      298,  298,  298,    3,  299,  299,    3,    7,  300,  300,
        7,    7,  297,   13,  301,  301,    7,    7,  302,  302,
      303,  303,    7,    7,  304,  304,  305,  305,  306,  306,
      307,  307,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,  308,  308,  309,  309,  297,  297,  297,  310,
      297,  297,  297,  297,  297,  297,  311,  311,  297,  297,
      312,  312,  297,  297,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  297,  314,  314,  314,  314,
      297,  315,  315,  316,  316,  317,  316,  297,  297,  318,
      319,  318,  320,  321,  320,  320,  322,  322,  323,  324,

      323,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      325,  325,  326,  327,  326,  310,  297,  297,  297,  297,
      297,  297,  311,  297,  328,  312,  297,  329,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  314,  330,  314,  314,  315,  316,  317,  297,
      331,  318,  319,  320,  320,  321,  321,  320,  322,  323,
      324,  297,  297,  297,  325,  326,  327,  297,  297,  297,
      297,  297,  297,  328,  329,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      330,  314,  314,  331,  321,  297,  297,  297,  297,  297,

      297,  297,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  314,  314,  297,  297,
      297,  297,  297,  297,  297,  297,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  314,  314,
      297,  297,  297,  297,  297,  297,  297,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  314,  314,  297,
      297,  297,  297,  297,  297,  297,  313,  313,  313,  313,
      313,  314,  314,  297,  297,  297,  297,  297,  297,  313,
      313,  313,  330,  297,  297,  297,  297,  297,  313,  330,
      297,  297,  313,  330,  297,  297,    0,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297
    } ;

static yyconst flex_int16_t yy_nxt[1753] =
    {   0,
      297,  297,   49,   50,  116,  148,  116,  148,  194,   63,
       64,   64,   64,   64,   64,   51,  175,   51,   51,   63,
       64,   64,   64,   64,   64,   81,  174,   51,   51,  294,
       51,  283,   48,   48,   48,   48,   48,   48,   81,  117,
      118,  119,   51,   51,  274,   48,   48,   48,   48,   48,
       48,   51,  130,   51,   49,   50,   88,   89,   89,   89,
       89,   89,  249,  118,  117,  244,  119,   51,  120,   51,
       51,   88,   89,   89,   89,   89,   89,  130,  102,   51,
       51,  211,   51,  200,  133,   48,   48,   48,   48,   48,
       48,  120,  138,  116,   51,   51,  144,  131,  103,  116,

      144,  146,  164,   51,  102,   51,   49,   50,   52,  133,
      132,   48,   48,   48,   48,   48,   48,  138,  134,   51,
      131,   53,   54,  103,  103,   55,  146,  164,  104,  142,
      155,   51,   51,  132,   51,   48,  105,   48,  105,   48,
       48,  134,   56,  163,  163,  144,   53,   54,  144,  103,
       55,  104,  142,  155,  157,   51,  155,   51,   48,  105,
       48,  105,   48,   48,  297,   56,   48,   48,   49,   50,
       48,   48,  170,   48,   48,  162,  297,  157,  110,  155,
      171,   51,   48,   58,   58,   48,   48,   48,   48,   48,
       48,  176,  106,   58,   58,  107,   58,  170,  162,   48,

       48,   48,   48,   48,   48,  171,  168,  169,   58,   58,
      124,  124,  124,  124,  124,  124,  176,   58,  297,   58,
       48,   48,   49,   50,   48,   48,  180,   48,   48,  168,
      169,  297,  110,  297,  181,   51,   48,   58,   58,   48,
       48,   48,   48,   48,   48,  188,  106,   58,   58,  107,
       58,  180,  172,   48,   48,   48,   48,   48,   48,  181,
      197,  284,   58,   58,  127,  127,  127,  127,  127,  127,
      188,   58,  144,   58,   48,  172,  199,  173,  144,   59,
       60,   60,   60,   60,   60,  197,  108,   51,   51,  109,
      297,   48,  145,   48,   48,   48,   48,   48,   48,  121,

      173,  199,  177,  122,  158,  297,  178,  155,   48,  290,
      290,  108,   51,   51,  109,  145,   48,  297,   48,   48,
       48,   48,   48,   48,  121,  177,  202,  158,  122,  178,
      155,   48,   48,   48,   49,   50,   48,   48,  179,  124,
      124,  124,  124,  124,  124,  297,  204,   51,   48,   62,
       62,  202,  127,  127,  127,  127,  127,  127,  297,   62,
       62,  179,   62,  150,  150,  150,  150,  150,  150,  125,
      182,  204,  297,  183,   62,   62,  124,  124,  124,  124,
      124,  124,  128,   62,  297,   62,   48,   48,   49,   50,
       48,   48,  125,  182,  184,  185,  139,  140,  183,  135,

      186,   51,   48,   62,   62,  128,  297,  136,  141,  137,
      187,  189,  190,   62,   62,  155,   62,  184,  185,  297,
      297,  139,  140,  186,  135,  297,  297,  297,   62,   62,
      136,  141,  137,  187,  189,  190,  297,   62,  155,   62,
       48,   48,   49,   50,   48,   48,   65,   48,   48,   65,
       65,   65,   65,   65,   65,   51,   48,   66,   67,   68,
       69,   70,   65,   65,   65,   71,   65,   72,   72,   65,
       72,   73,   65,   65,   65,   74,   75,   65,   65,   65,
       65,   65,   66,   67,   68,   69,   70,   65,   65,   65,
       71,   72,   65,   72,   73,   65,   65,   65,   74,   75,

       65,   65,   65,   65,   48,   48,   76,   50,   48,   48,
      144,   48,   48,  127,  127,  127,  127,  127,  127,   51,
       48,   78,   78,  144,  297,   79,  192,  297,   80,  193,
      297,   78,   78,  157,   78,  297,  297,  150,  150,  150,
      150,  150,  150,  297,  205,  158,   78,   78,  155,  155,
       79,  192,  193,   80,  196,   78,  157,   78,   48,   48,
       76,   50,   48,   48,  198,   48,   48,  151,  158,  205,
      297,  155,  155,   51,   48,   78,   78,  196,  297,   79,
      195,  297,   80,  157,  297,   78,   78,  198,   78,  297,
      151,  150,  150,  150,  150,  150,  150,  201,  203,  206,

       78,   78,  212,  195,   79,  297,  157,   80,  207,   78,
      208,   78,   48,   48,   49,   50,   48,   48,  209,   48,
      201,  203,  210,  213,  206,  212,  214,   51,   48,   83,
       83,  216,  297,  207,  215,  208,  144,  157,  297,   83,
       83,  219,   83,  209,  144,  297,  297,  210,  213,  214,
      221,  220,  297,  222,   83,   83,  216,  215,  297,  297,
      157,  218,  217,   83,  219,   83,   48,   48,   49,   50,
       48,   48,  225,   48,  220,  221,  222,  223,  226,  224,
      227,   51,   48,   83,   83,  217,  297,  228,  229,  230,
      231,  232,  144,   83,   83,  235,   83,  225,  234,  237,

      223,  226,  224,  236,  238,  227,  233,  144,   83,   83,
      228,  229,  240,  241,  230,  231,  232,   83,  235,   83,
       48,   85,   86,  234,  237,  242,  236,  238,  243,  233,
      297,  239,  245,  246,   87,  240,   87,   87,  241,  297,
      247,  248,  250,  251,  252,  253,   87,   87,  242,   87,
      297,  256,  257,  243,  239,  245,  254,  255,  246,  144,
      259,   87,   87,  247,  248,  144,  251,  250,  253,  252,
       87,  260,   87,   48,   85,   86,  256,  257,  261,  254,
      255,  258,  262,  265,  263,  259,  264,   87,  266,   87,
       87,  297,  268,  267,  260,  269,  270,  271,  297,   87,

       87,  276,   87,  261,  258,  262,  265,  263,  277,  264,
      275,  266,  144,  144,   87,   87,  267,  268,  269,  273,
      278,  270,  271,   87,  276,   87,   48,   49,   91,  279,
      297,  277,  297,  272,  280,  275,  281,  282,  285,  297,
       92,  286,   92,   92,  273,  278,  287,  288,  289,  291,
      297,  297,   92,   92,  279,   92,  272,  280,  297,  281,
      292,  293,  282,  285,  286,  295,  296,   92,   92,  287,
      288,  297,  297,  289,  291,  297,   92,  297,   92,   48,
       49,   91,  297,  292,  293,  297,  297,  297,  295,  296,
      297,  297,  297,   92,  297,   92,   92,  297,  297,  297,

      297,  297,  297,  297,  297,   92,   92,  297,   92,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
       92,   92,  297,  297,  297,  297,  297,  297,  297,   92,
      297,   92,   49,   94,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,   95,  297,   95,   95,  297,
      297,  297,  297,  297,  297,  297,  297,   95,   95,  297,
       95,  297,  297,   96,  297,  297,  297,  297,  297,  297,
      297,  297,   95,   95,  297,  297,  297,  297,  297,  297,
      297,   95,  297,   95,  297,  297,   96,   49,   94,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

       95,  297,   95,   95,  297,  297,  297,  297,  297,  297,
      297,  297,   95,   95,  297,   95,  297,  297,   96,  297,
      297,  297,  297,  297,  297,  297,  297,   95,   95,  297,
      297,  297,  297,  297,  297,  297,   95,  297,   95,  297,
      297,   96,   48,   48,   49,   50,   48,   48,  297,   48,
       48,  297,  297,  297,  297,  297,  297,   51,   48,   98,
       98,  297,  297,  297,  297,  297,  297,  297,  297,   98,
       98,  297,   98,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,   98,   98,  297,  297,  297,  297,
      297,  297,  297,   98,  297,   98,   48,   48,   49,   50,

       48,   48,  297,   48,   48,  297,  297,  297,  297,  297,
      297,   51,   48,   98,   98,  297,  297,  297,  297,  297,
      297,  297,  297,   98,   98,  297,   98,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,   98,   98,
      297,  297,  297,  297,  297,  297,  297,   98,  297,   98,
       49,  100,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  101,  297,  101,  101,  297,  297,  297,
      297,  297,  297,  297,  297,  101,  101,  297,  101,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      101,  101,  297,  297,  297,  297,  297,  297,  297,  101,

      297,  101,   49,  100,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  101,  297,  101,  101,  297,
      297,  297,  297,  297,  297,  297,  297,  101,  101,  297,
      101,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  101,  101,  297,  297,  297,  297,  297,  297,
      297,  101,  297,  101,   48,   48,   49,   50,   48,   48,
      297,   48,   48,  297,  297,  297,  297,  297,  297,   51,
       48,  112,  112,  297,  297,  297,  297,  297,  297,  297,
      297,  112,  112,  297,  112,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  112,  112,  297,  297,

      297,  297,  297,  297,  297,  112,  297,  112,   48,   48,
       49,   50,   48,   48,  297,   48,   48,  297,  297,  297,
      297,  297,  297,   51,   48,  112,  112,  297,  297,  297,
      297,  297,  297,  297,  297,  112,  112,  297,  112,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      112,  112,  297,  297,  297,  297,  297,  297,  297,  112,
      297,  112,   49,  114,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  115,  297,  115,  115,  297,
      297,  297,  297,  297,  297,  297,  297,  115,  115,  297,
      115,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  115,  115,  297,  297,  297,  297,  297,  297,
      297,  115,  297,  115,   49,  114,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  115,  297,  115,
      115,  297,  297,  297,  297,  297,  297,  297,  297,  115,
      115,  297,  115,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  115,  115,  297,  297,  297,  297,
      297,  297,  297,  115,  297,  115,   48,   48,   48,   48,
       48,   48,   48,   48,   57,   57,   57,   57,   57,   57,
       57,   57,   61,   61,   61,   61,   61,   61,   61,   61,
       77,   77,   77,   77,   77,   77,   77,   77,   82,   82,

       82,   82,   82,   82,   82,   82,   84,   84,   84,   84,
       84,   84,   84,   84,   90,   90,   90,   90,   90,   90,
       90,   90,   93,   93,   93,   93,   93,   93,   93,   93,
       97,   97,   97,   97,   97,   97,   97,   97,   99,   99,
       99,   99,   99,   99,   99,   99,  111,  111,  111,  111,
      111,  111,  111,  111,  113,  113,  113,  113,  113,  113,
      113,  113,  116,  116,  297,  116,  116,  116,  116,  116,
      123,  297,  297,  123,  126,  126,  126,  126,  129,  297,
      297,  129,  143,  297,  297,  143,  143,  147,  297,  147,
      147,  148,  297,  148,  148,  148,  148,  148,  148,  149,

      149,  149,  149,  149,  149,  149,  149,  152,  297,  297,
      152,  152,  152,  152,  152,  153,  153,  297,  153,  153,
      153,  153,  153,  154,  154,  297,  154,  154,  154,  154,
      154,  156,  156,  297,  156,  156,  156,  156,  156,  159,
      297,  297,  159,  160,  160,  297,  160,  160,  160,  160,
      160,  161,  161,  297,  161,  161,  161,  161,  161,  165,
      297,  297,  165,  166,  166,  297,  166,  166,  166,  166,
      166,  167,  167,  297,  167,  167,  167,  167,  167,  191,
      191,  297,  191,  191,  191,  191,  191,   47,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297
    } ;

static yyconst flex_int16_t yy_chk[1753] =
    {   0,
        0,    0,    1,    1,   86,   86,  149,  149,  331,   11,
       11,   11,   11,   11,   11,    1,  329,    1,    1,   12,
       12,   12,   12,   12,   12,   17,  328,    1,    1,  290,
        1,  272,   17,   17,   17,   17,   17,   17,   18,   52,
       53,   54,    1,    1,  260,   18,   18,   18,   18,   18,
       18,    1,   66,    1,    2,    2,   23,   23,   23,   23,
       23,   23,  228,   53,   52,  222,   54,    2,   55,    2,
        2,   24,   24,   24,   24,   24,   24,   66,   33,    2,
        2,  184,    2,  171,   69,   33,   33,   33,   33,   33,
       33,   55,   73,  153,    2,    2,  143,   67,   33,   91,

       80,   80,  109,    2,   34,    2,    3,    3,    3,   69,
       68,   34,   34,   34,   34,   34,   34,   73,   70,    3,
       67,    3,    3,   33,   34,    3,   80,  109,   35,   75,
       93,    3,    3,   68,    3,   35,   35,   35,   35,   35,
       35,   70,    3,  107,  107,   78,    3,    3,   77,   34,
        3,   36,   75,   93,   94,    3,   95,    3,   36,   36,
       36,   36,   36,   36,   47,    3,    5,    5,    5,    5,
        5,    5,  119,    5,    5,  103,    0,   94,   41,   95,
      120,    5,    5,    5,    5,   41,   41,   41,   41,   41,
       41,  130,   37,    5,    5,   37,    5,  119,  103,   37,

       37,   37,   37,   37,   37,  120,  117,  118,    5,    5,
       60,   60,   60,   60,   60,   60,  130,    5,    0,    5,
        6,    6,    6,    6,    6,    6,  134,    6,    6,  117,
      118,    0,   42,    0,  135,    6,    6,    6,    6,   42,
       42,   42,   42,   42,   42,  140,   38,    6,    6,   38,
        6,  134,  121,   38,   38,   38,   38,   38,   38,  135,
      168,  273,    6,    6,   64,   64,   64,   64,   64,   64,
      140,    6,  273,    6,    7,  121,  170,  122,   79,    7,
        7,    7,    7,    7,    7,  168,   39,    7,    7,   39,
        0,    7,   79,   39,   39,   39,   39,   39,   39,   56,

      122,  170,  131,   56,   96,    0,  132,   96,    7,  283,
      283,   40,    7,    7,   40,   79,    7,    0,   40,   40,
       40,   40,   40,   40,   56,  131,  173,   96,   56,  132,
       96,    7,    9,    9,    9,    9,    9,    9,  133,   59,
       59,   59,   59,   59,   59,    0,  177,    9,    9,    9,
        9,  173,   63,   63,   63,   63,   63,   63,    0,    9,
        9,  133,    9,   89,   89,   89,   89,   89,   89,   59,
      136,  177,    0,  137,    9,    9,  124,  124,  124,  124,
      124,  124,   63,    9,    0,    9,   10,   10,   10,   10,
       10,   10,   59,  136,  137,  137,   74,   74,  137,   71,

      138,   10,   10,   10,   10,   63,    0,   71,   74,   71,
      139,  141,  142,   10,   10,  154,   10,  137,  137,    0,
        0,   74,   74,  138,   71,    0,    0,    0,   10,   10,
       71,   74,   71,  139,  141,  142,    0,   10,  154,   10,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   15,   15,   15,   15,   15,   15,
      146,   15,   15,  127,  127,  127,  127,  127,  127,   15,
       15,   15,   15,  145,    0,   15,  145,    0,   15,  146,
        0,   15,   15,  156,   15,    0,    0,   88,   88,   88,
       88,   88,   88,    0,  178,  155,   15,   15,  155,  158,
       15,  145,  146,   15,  162,   15,  156,   15,   16,   16,
       16,   16,   16,   16,  169,   16,   16,   88,  155,  178,
        0,  155,  158,   16,   16,   16,   16,  162,    0,   16,
      157,    0,   16,  157,    0,   16,   16,  169,   16,    0,
       88,  150,  150,  150,  150,  150,  150,  172,  176,  179,

       16,   16,  185,  157,   16,    0,  157,   16,  180,   16,
      181,   16,   19,   19,   19,   19,   19,   19,  182,   19,
      172,  176,  183,  186,  179,  185,  187,   19,   19,   19,
       19,  189,    0,  180,  188,  181,  193,  195,    0,   19,
       19,  196,   19,  182,  192,    0,    0,  183,  186,  187,
      198,  197,    0,  199,   19,   19,  189,  188,    0,    0,
      195,  193,  192,   19,  196,   19,   20,   20,   20,   20,
       20,   20,  201,   20,  197,  198,  199,  200,  202,  200,
      203,   20,   20,   20,   20,  192,    0,  205,  207,  209,
      210,  211,  218,   20,   20,  213,   20,  201,  212,  215,

      200,  202,  200,  214,  216,  203,  211,  217,   20,   20,
      205,  207,  218,  219,  209,  210,  211,   20,  213,   20,
       21,   21,   21,  212,  215,  220,  214,  216,  221,  211,
        0,  217,  223,  224,   21,  218,   21,   21,  219,    0,
      226,  227,  230,  231,  232,  233,   21,   21,  220,   21,
        0,  237,  238,  221,  217,  223,  234,  235,  224,  240,
      240,   21,   21,  226,  227,  239,  231,  230,  233,  232,
       21,  241,   21,   22,   22,   22,  237,  238,  242,  234,
      235,  239,  243,  245,  244,  240,  244,   22,  246,   22,
       22,    0,  249,  248,  241,  250,  252,  253,    0,   22,

       22,  262,   22,  242,  239,  243,  245,  244,  263,  244,
      261,  246,  259,  258,   22,   22,  248,  249,  250,  259,
      264,  252,  253,   22,  262,   22,   25,   25,   25,  266,
        0,  263,    0,  258,  268,  261,  270,  271,  276,    0,
       25,  277,   25,   25,  259,  264,  278,  279,  282,  287,
        0,    0,   25,   25,  266,   25,  258,  268,    0,  270,
      288,  289,  271,  276,  277,  291,  295,   25,   25,  278,
      279,    0,    0,  282,  287,    0,   25,    0,   25,   26,
       26,   26,    0,  288,  289,    0,    0,    0,  291,  295,
        0,    0,    0,   26,    0,   26,   26,    0,    0,    0,

        0,    0,    0,    0,    0,   26,   26,    0,   26,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       26,   26,    0,    0,    0,    0,    0,    0,    0,   26,
        0,   26,   27,   27,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   27,    0,   27,   27,    0,
        0,    0,    0,    0,    0,    0,    0,   27,   27,    0,
       27,    0,    0,   27,    0,    0,    0,    0,    0,    0,
        0,    0,   27,   27,    0,    0,    0,    0,    0,    0,
        0,   27,    0,   27,    0,    0,   27,   28,   28,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       28,    0,   28,   28,    0,    0,    0,    0,    0,    0,
        0,    0,   28,   28,    0,   28,    0,    0,   28,    0,
        0,    0,    0,    0,    0,    0,    0,   28,   28,    0,
        0,    0,    0,    0,    0,    0,   28,    0,   28,    0,
        0,   28,   29,   29,   29,   29,   29,   29,    0,   29,
       29,    0,    0,    0,    0,    0,    0,   29,   29,   29,
       29,    0,    0,    0,    0,    0,    0,    0,    0,   29,
       29,    0,   29,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   29,   29,    0,    0,    0,    0,
        0,    0,    0,   29,    0,   29,   30,   30,   30,   30,

       30,   30,    0,   30,   30,    0,    0,    0,    0,    0,
        0,   30,   30,   30,   30,    0,    0,    0,    0,    0,
        0,    0,    0,   30,   30,    0,   30,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   30,   30,
        0,    0,    0,    0,    0,    0,    0,   30,    0,   30,
       31,   31,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   31,    0,   31,   31,    0,    0,    0,
        0,    0,    0,    0,    0,   31,   31,    0,   31,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       31,   31,    0,    0,    0,    0,    0,    0,    0,   31,

        0,   31,   32,   32,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   32,    0,   32,   32,    0,
        0,    0,    0,    0,    0,    0,    0,   32,   32,    0,
       32,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   32,   32,    0,    0,    0,    0,    0,    0,
        0,   32,    0,   32,   43,   43,   43,   43,   43,   43,
        0,   43,   43,    0,    0,    0,    0,    0,    0,   43,
       43,   43,   43,    0,    0,    0,    0,    0,    0,    0,
        0,   43,   43,    0,   43,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   43,   43,    0,    0,

        0,    0,    0,    0,    0,   43,    0,   43,   44,   44,
       44,   44,   44,   44,    0,   44,   44,    0,    0,    0,
        0,    0,    0,   44,   44,   44,   44,    0,    0,    0,
        0,    0,    0,    0,    0,   44,   44,    0,   44,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       44,   44,    0,    0,    0,    0,    0,    0,    0,   44,
        0,   44,   45,   45,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,    0,   45,   45,    0,
        0,    0,    0,    0,    0,    0,    0,   45,   45,    0,
       45,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   45,   45,    0,    0,    0,    0,    0,    0,
        0,   45,    0,   45,   46,   46,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   46,    0,   46,
       46,    0,    0,    0,    0,    0,    0,    0,    0,   46,
       46,    0,   46,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   46,   46,    0,    0,    0,    0,
        0,    0,    0,   46,    0,   46,  298,  298,  298,  298,
      298,  298,  298,  298,  299,  299,  299,  299,  299,  299,
      299,  299,  300,  300,  300,  300,  300,  300,  300,  300,
      301,  301,  301,  301,  301,  301,  301,  301,  302,  302,

      302,  302,  302,  302,  302,  302,  303,  303,  303,  303,
      303,  303,  303,  303,  304,  304,  304,  304,  304,  304,
      304,  304,  305,  305,  305,  305,  305,  305,  305,  305,
      306,  306,  306,  306,  306,  306,  306,  306,  307,  307,
      307,  307,  307,  307,  307,  307,  308,  308,  308,  308,
      308,  308,  308,  308,  309,  309,  309,  309,  309,  309,
      309,  309,  310,  310,    0,  310,  310,  310,  310,  310,
      311,    0,    0,  311,  312,  312,  312,  312,  313,    0,
        0,  313,  314,    0,    0,  314,  314,  315,    0,  315,
      315,  316,    0,  316,  316,  316,  316,  316,  316,  317,

      317,  317,  317,  317,  317,  317,  317,  318,    0,    0,
      318,  318,  318,  318,  318,  319,  319,    0,  319,  319,
      319,  319,  319,  320,  320,    0,  320,  320,  320,  320,
      320,  321,  321,    0,  321,  321,  321,  321,  321,  322,
        0,    0,  322,  323,  323,    0,  323,  323,  323,  323,
      323,  324,  324,    0,  324,  324,  324,  324,  324,  325,
        0,    0,  325,  326,  326,    0,  326,  326,  326,  326,
      326,  327,  327,    0,  327,  327,  327,  327,  327,  330,
      330,    0,  330,  330,  330,  330,  330,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int Radius_flex_debug;
int Radius_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Radiustext;
#line 1 "radius_dict.l"
/*
 * We don't use input, so don't generate code for it.
 */
#define YY_NO_INPUT 1
/*
 * We don't use unput, so don't generate code for it.
 */
/*
 * We don't read from the terminal.
 */
/*
 * The language we're scanning is case-insensitive.
 */
/*
 * Prefix scanner routines with "Radius" rather than "yy", so this scanner
 * can coexist with other scanners.
 */
#line 30 "radius_dict.l"
	/* radius_dict.l
	*
	* RADIUS dictionary parser
	*
	* $Id$
	*
	* Wireshark - Network traffic analyzer
	* By Gerald Combs <gerald@wireshark.org>
	* Copyright 1998 Gerald Combs
	*
	* This program is free software; you can redistribute it and/or
	* modify it under the terms of the GNU General Public License
	* as published by the Free Software Foundation; either version 2
	* of the License, or (at your option) any later version.
	*
	* This program is distributed in the hope that it will be useful,
	* but WITHOUT ANY WARRANTY; without even the implied warranty of
	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	* GNU General Public License for more details.
	*
	* You should have received a copy of the GNU General Public License
	* along with this program; if not, write to the Free Software
	* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
	*/

#include "config.h"

#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <epan/packet.h>
#include <epan/dissectors/packet-radius.h>
#include "radius_dict_lex.h"
#include <wsutil/file_util.h>

#ifdef _WIN32
/* disable Windows VC compiler warning "signed/unsigned mismatch" associated  */
/* with YY_INPUT code generated by flex versions such as 2.5.35.              */
#pragma warning (disable:4018)
#endif

#define ECHO
#define MAX_INCLUDE_DEPTH 10

	static void add_vendor(const gchar* name, guint32 id, guint type_octets, guint length_octets, gboolean has_flags);
	static void add_value(const gchar* attrib_name,const  gchar* repr, long value);
	static void add_tlv(const gchar* name, const  gchar* code, radius_attr_dissector_t type, const gchar* attr);
	static void add_attribute(const gchar*,const  gchar*, radius_attr_dissector_t,const  gchar*, guint, gboolean, const gchar*);

	static YY_BUFFER_STATE include_stack[10];
	static int include_stack_ptr = 0;

	static radius_dictionary_t* dict = NULL;
	static GHashTable* value_strings = NULL; /* GArray(value_string) by attribute name */

	static gchar* attr_name = NULL;
	static gchar* attr_id = NULL;
	static radius_attr_dissector_t* attr_type = NULL;
	static gchar* attr_vendor = NULL;
	static gchar* vendor_name = NULL;
	static guint32 vendor_id = 0;
	static guint vendor_type_octets = 1;
	static guint vendor_length_octets = 1;
	static gboolean vendor_has_flags = FALSE;
	static gchar* value_repr = NULL;
	static guint encrypted = 0;
	static gboolean has_tag = FALSE;
	static gchar* current_vendor = NULL;
	static gchar* current_attr = NULL;

	static GString* error = NULL;
	static gchar* directory = NULL;
	static int linenums[] = {1,1,1,1,1,1,1,1,1,1};
	static gchar* fullpaths[] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

/* Note: FreeRadius allows VENDOR, ATTRIBUTE and VALUE names to contain any non-blank character.
 *       Using a negated "blank character class" pattern below for those names fails for some reason
 *       so for now the patterns for each name type include those characters found for the corresponding
 *       name types in the FreeRadius dictionaries.
 */

#line 1073 "radius_dict.c"

#define INITIAL 0
#define WS_OUT 1
#define VENDOR 2
#define VENDOR_W_NAME 3
#define ATTR 4
#define ATTR_W_NAME 5
#define ATTR_W_ID 6
#define ATTR_W_TYPE 7
#define ATTR_W_VENDOR 8
#define VALUE 9
#define VALUE_W_ATTR 10
#define VALUE_W_NAME 11
#define INCLUDE 12
#define JUNK 13
#define BEGIN_VENDOR 14
#define END_VENDOR 15
#define VENDOR_W_ID 16
#define VENDOR_W_FORMAT 17
#define VENDOR_W_TYPE_OCTETS 18
#define VENDOR_W_LENGTH_OCTETS 19
#define VENDOR_W_CONTINUATION 20
#define BEGIN_TLV 21
#define END_TLV 22

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Radiuslex_destroy (void );

int Radiusget_debug (void );

void Radiusset_debug (int debug_flag  );

YY_EXTRA_TYPE Radiusget_extra (void );

void Radiusset_extra (YY_EXTRA_TYPE user_defined  );

FILE *Radiusget_in (void );

void Radiusset_in  (FILE * in_str  );

FILE *Radiusget_out (void );

void Radiusset_out  (FILE * out_str  );

int Radiusget_leng (void );

char *Radiusget_text (void );

int Radiusget_lineno (void );

void Radiusset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Radiuswrap (void );
#else
extern int Radiuswrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( Radiustext, Radiusleng, 1, Radiusout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Radiusin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Radiusin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, Radiusin))==0 && ferror(Radiusin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Radiusin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Radiuslex (void);

#define YY_DECL int Radiuslex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Radiustext and Radiusleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 116 "radius_dict.l"

#line 1282 "radius_dict.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! Radiusin )
			Radiusin = stdin;

		if ( ! Radiusout )
			Radiusout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Radiusensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Radius_create_buffer(Radiusin,YY_BUF_SIZE );
		}

		Radius_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of Radiustext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 298 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 297 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 117 "radius_dict.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 118 "radius_dict.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 120 "radius_dict.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 122 "radius_dict.l"
{ BEGIN VENDOR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 123 "radius_dict.l"
{ BEGIN ATTR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "radius_dict.l"
{ BEGIN VALUE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "radius_dict.l"
{ BEGIN INCLUDE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 126 "radius_dict.l"
{ BEGIN BEGIN_VENDOR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "radius_dict.l"
{ BEGIN END_VENDOR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "radius_dict.l"
{ BEGIN BEGIN_TLV; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "radius_dict.l"
{ BEGIN END_TLV; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 131 "radius_dict.l"
{
    if (current_vendor) {
        g_free(current_vendor);
    }
    current_vendor = g_strdup(Radiustext);
    BEGIN WS_OUT;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "radius_dict.l"
{
    if (current_vendor) {
        g_free(current_vendor);
        current_vendor = NULL;
    }
    BEGIN WS_OUT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 146 "radius_dict.l"
{
    if (current_attr) {
        g_free(current_attr);
    }
    current_attr = g_strdup(Radiustext);
    BEGIN WS_OUT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 153 "radius_dict.l"
{
    if (current_attr) {
        g_free(current_attr);
        current_attr = NULL;
    }
    BEGIN WS_OUT;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 161 "radius_dict.l"
{
    vendor_name = g_strdup(Radiustext);
    vendor_type_octets = 1;
    vendor_length_octets = 1;
    vendor_has_flags = FALSE;
    BEGIN VENDOR_W_NAME;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 168 "radius_dict.l"
{
    vendor_id = strtol(Radiustext,NULL,10);
    BEGIN VENDOR_W_ID;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 172 "radius_dict.l"
{
    vendor_id = strtol(Radiustext,NULL,16);
    BEGIN VENDOR_W_ID;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 176 "radius_dict.l"
{
    BEGIN VENDOR_W_FORMAT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 179 "radius_dict.l"
{
    vendor_type_octets = strtol(Radiustext,NULL,10);
    BEGIN VENDOR_W_TYPE_OCTETS;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 183 "radius_dict.l"
{
    vendor_length_octets = strtol(Radiustext+1,NULL,10);
    BEGIN VENDOR_W_LENGTH_OCTETS;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 187 "radius_dict.l"
{
    vendor_has_flags = TRUE;
    BEGIN VENDOR_W_CONTINUATION;
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
#line 192 "radius_dict.l"
case 24:
/* rule 24 can match eol */
#line 193 "radius_dict.l"
case 25:
/* rule 25 can match eol */
#line 194 "radius_dict.l"
case 26:
/* rule 26 can match eol */
#line 195 "radius_dict.l"
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 195 "radius_dict.l"
{
    add_vendor(vendor_name, vendor_id, vendor_type_octets, vendor_length_octets, vendor_has_flags);
    g_free(vendor_name);
    BEGIN WS_OUT;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 201 "radius_dict.l"
{ attr_name = g_strdup(Radiustext); encrypted = 0; has_tag = FALSE; BEGIN ATTR_W_NAME; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 202 "radius_dict.l"
{ attr_id = g_strdup(Radiustext);  BEGIN ATTR_W_ID;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 203 "radius_dict.l"
{ attr_id = g_strdup_printf("%u",(int)strtoul(Radiustext,NULL,16)); BEGIN ATTR_W_ID;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 204 "radius_dict.l"
{ attr_type = radius_integer;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "radius_dict.l"
{ attr_type = radius_string;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 206 "radius_dict.l"
{ attr_type = radius_octets;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 207 "radius_dict.l"
{ attr_type = radius_ipaddr;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 208 "radius_dict.l"
{ attr_type = radius_ipv6addr;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 209 "radius_dict.l"
{ attr_type = radius_ipv6prefix;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 210 "radius_dict.l"
{ attr_type = radius_ipxnet;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 211 "radius_dict.l"
{ attr_type = radius_date;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 212 "radius_dict.l"
{ attr_type = radius_abinary;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 213 "radius_dict.l"
{ attr_type = radius_ether;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 214 "radius_dict.l"
{ attr_type = radius_ifid;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 215 "radius_dict.l"
{ attr_type = radius_integer;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 216 "radius_dict.l"
{ attr_type = radius_integer;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 217 "radius_dict.l"
{ attr_type = radius_signed;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 218 "radius_dict.l"
{ attr_type = radius_combo_ip;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 219 "radius_dict.l"
{ attr_type = radius_tlv;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 220 "radius_dict.l"
{ attr_type = radius_octets;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 221 "radius_dict.l"
{ has_tag = TRUE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "radius_dict.l"
{ encrypted = strtol(Radiustext+8,NULL,10); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 223 "radius_dict.l"
;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 224 "radius_dict.l"
{
    attr_vendor = g_strdup(Radiustext);
    add_attribute(attr_name,attr_id,attr_type,attr_vendor,encrypted,has_tag,current_attr);
    g_free(attr_id);
    g_free(attr_vendor);
    g_free(attr_name);
    attr_id = NULL;
    attr_vendor = NULL;
    attr_name = NULL;
    BEGIN WS_OUT;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 235 "radius_dict.l"
{
    add_attribute(attr_name,attr_id,attr_type,current_vendor,encrypted,has_tag,current_attr);
    g_free(attr_id);
    g_free(attr_name);
    linenums[include_stack_ptr]++;
    has_tag = FALSE;
    encrypted=FALSE;
    BEGIN WS_OUT;
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 244 "radius_dict.l"
{
    add_attribute(attr_name,attr_id,attr_type,attr_vendor,encrypted,has_tag,current_attr);
    g_free(attr_id);
    g_free(attr_vendor);
    g_free(attr_name);
    linenums[include_stack_ptr]++;
    BEGIN WS_OUT;
};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 253 "radius_dict.l"
{ attr_name = g_strdup(Radiustext); BEGIN VALUE_W_ATTR; }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 254 "radius_dict.l"
{ value_repr = g_strdup(Radiustext); BEGIN VALUE_W_NAME; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 255 "radius_dict.l"
{ add_value(attr_name,value_repr,strtol(Radiustext,NULL,10));  g_free(attr_name); g_free(value_repr); BEGIN WS_OUT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 256 "radius_dict.l"
{ add_value(attr_name,value_repr,strtol(Radiustext,NULL,16));  g_free(attr_name); g_free(value_repr); BEGIN WS_OUT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 258 "radius_dict.l"
{
	if ( include_stack_ptr >= MAX_INCLUDE_DEPTH ) {
		g_string_append_printf(error, "$INCLUDE files nested to deeply\n");
		yyterminate();
	}

	include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;

	fullpaths[include_stack_ptr] = g_strdup_printf("%s" G_DIR_SEPARATOR_S "%s",
	    directory,Radiustext);

	Radiusin = ws_fopen( fullpaths[include_stack_ptr], "r" );

	if (!Radiusin) {
		if (errno) {
			g_string_append_printf(error,
					"Could not open file: '%s', error: %s\n",
					fullpaths[include_stack_ptr],
					g_strerror(errno) );
		} else {
			g_string_append_printf(error,
					"Could not open file: '%s', no errno\n",
					fullpaths[include_stack_ptr]);
		}
		g_free(fullpaths[include_stack_ptr]);
		fullpaths[include_stack_ptr] = NULL;
		include_stack_ptr--;
	} else {
		linenums[include_stack_ptr] = 1;
		Radius_switch_to_buffer(Radius_create_buffer(Radiusin,YY_BUF_SIZE ) );
	}


	BEGIN WS_OUT;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(WS_OUT):
case YY_STATE_EOF(VENDOR):
case YY_STATE_EOF(VENDOR_W_NAME):
case YY_STATE_EOF(ATTR):
case YY_STATE_EOF(ATTR_W_NAME):
case YY_STATE_EOF(ATTR_W_ID):
case YY_STATE_EOF(ATTR_W_TYPE):
case YY_STATE_EOF(ATTR_W_VENDOR):
case YY_STATE_EOF(VALUE):
case YY_STATE_EOF(VALUE_W_ATTR):
case YY_STATE_EOF(VALUE_W_NAME):
case YY_STATE_EOF(INCLUDE):
case YY_STATE_EOF(JUNK):
case YY_STATE_EOF(BEGIN_VENDOR):
case YY_STATE_EOF(END_VENDOR):
case YY_STATE_EOF(VENDOR_W_ID):
case YY_STATE_EOF(VENDOR_W_FORMAT):
case YY_STATE_EOF(VENDOR_W_TYPE_OCTETS):
case YY_STATE_EOF(VENDOR_W_LENGTH_OCTETS):
case YY_STATE_EOF(VENDOR_W_CONTINUATION):
case YY_STATE_EOF(BEGIN_TLV):
case YY_STATE_EOF(END_TLV):
#line 294 "radius_dict.l"
{

	fclose(Radiusin);
	Radiusin = NULL;

	if ( --include_stack_ptr < 0 ) {
		yyterminate();
	} else {
		g_free(fullpaths[include_stack_ptr+1]);
		fullpaths[include_stack_ptr+1] = NULL;

		Radius_delete_buffer(YY_CURRENT_BUFFER );
		Radius_switch_to_buffer(include_stack[include_stack_ptr]);
	}

	BEGIN WS_OUT;
}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 312 "radius_dict.l"
{ linenums[include_stack_ptr]++; BEGIN WS_OUT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 315 "radius_dict.l"
ECHO;
	YY_BREAK
#line 1810 "radius_dict.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Radiusin at a new source and called
			 * Radiuslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = Radiusin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( Radiuswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * Radiustext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of Radiuslex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Radiusrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Radiusrestart(Radiusin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Radiusrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 298 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 298 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 297);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Radiusrestart(Radiusin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Radiuswrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve Radiustext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Radiusrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Radiusensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Radius_create_buffer(Radiusin,YY_BUF_SIZE );
	}

	Radius_init_buffer(YY_CURRENT_BUFFER,input_file );
	Radius_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Radius_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Radiuspop_buffer_state();
	 *		Radiuspush_buffer_state(new_buffer);
     */
	Radiusensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Radius_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (Radiuswrap()) processing, but the only time this flag
	 * is looked at is after Radiuswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void Radius_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	Radiusin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Radius_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Radiusalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Radiusalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_create_buffer()" );

	b->yy_is_our_buffer = 1;

	Radius_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Radius_create_buffer()
 * 
 */
    void Radius_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Radiusfree((void *) b->yy_ch_buf  );

	Radiusfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Radiusrestart() or at EOF.
 */
    static void Radius_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Radius_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then Radius_init_buffer was _probably_
     * called from Radiusrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Radius_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Radius_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Radiuspush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Radiusensure_buffer_stack();

	/* This block is copied from Radius_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Radius_switch_to_buffer. */
	Radius_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Radiuspop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Radius_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Radius_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Radiusensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)Radiusalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Radiusensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)Radiusrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Radiusensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE Radius_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) Radiusalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	Radius_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Radiuslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Radius_scan_bytes() instead.
 */
YY_BUFFER_STATE Radius_scan_string (yyconst char * yystr )
{
    
	return Radius_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Radiuslex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Radius_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) Radiusalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Radius_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Radius_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Radiustext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		Radiustext[Radiusleng] = (yy_hold_char); \
		(yy_c_buf_p) = Radiustext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		Radiusleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Radiusget_lineno  (void)
{
        
    return Radiuslineno;
}

/** Get the input stream.
 * 
 */
FILE *Radiusget_in  (void)
{
        return Radiusin;
}

/** Get the output stream.
 * 
 */
FILE *Radiusget_out  (void)
{
        return Radiusout;
}

/** Get the length of the current token.
 * 
 */
int Radiusget_leng  (void)
{
        return Radiusleng;
}

/** Get the current token.
 * 
 */

char *Radiusget_text  (void)
{
        return Radiustext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void Radiusset_lineno (int  line_number )
{
    
    Radiuslineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see Radius_switch_to_buffer
 */
void Radiusset_in (FILE *  in_str )
{
        Radiusin = in_str ;
}

void Radiusset_out (FILE *  out_str )
{
        Radiusout = out_str ;
}

int Radiusget_debug  (void)
{
        return Radius_flex_debug;
}

void Radiusset_debug (int  bdebug )
{
        Radius_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Radiuslex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Radiusin = stdin;
    Radiusout = stdout;
#else
    Radiusin = (FILE *) 0;
    Radiusout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Radiuslex_init()
     */
    return 0;
}

/* Radiuslex_destroy is for both reentrant and non-reentrant scanners. */
int Radiuslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Radius_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Radiuspop_buffer_state();
	}

	/* Destroy the stack itself. */
	Radiusfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Radiuslex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Radiusalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *Radiusrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void Radiusfree (void * ptr )
{
	free( (char *) ptr );	/* see Radiusrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 315 "radius_dict.l"



static void add_vendor(const gchar* name, guint32 id, guint type_octets, guint length_octets, gboolean has_flags) {
	radius_vendor_info_t* v;

	v = (radius_vendor_info_t *)g_hash_table_lookup(dict->vendors_by_id, GUINT_TO_POINTER(id));

	if (!v) {
		v = g_new(radius_vendor_info_t,1);
		v->attrs_by_id = g_hash_table_new(g_direct_hash,g_direct_equal);
		v->code = id;
		v->ett = -1;
		v->name = NULL;
	}
        /* Assume that the dictionary knows the 'ground truth' about the
         * type/length/has_flags information and thus allow the dictionary to
         * overwrite these values even for vendors that have already been loaded.
         */
	v->type_octets = type_octets;
	v->length_octets = length_octets;
	v->has_flags = has_flags;

	if (v->name)
		g_free((gpointer) v->name);
	v->name = g_strdup(name);

	g_hash_table_insert(dict->vendors_by_id,GUINT_TO_POINTER(v->code),v);
	g_hash_table_insert(dict->vendors_by_name, (gpointer) v->name, v);
}

static void add_attribute(const gchar* name, const  gchar* codestr, radius_attr_dissector_t type, const  gchar* vendor, guint encrypted_flag, gboolean tagged, const gchar* attr) {
	radius_attr_info_t* a;
	GHashTable* by_id;
	guint32 code;
	const gchar *tmpName = NULL;


	if (attr){
		add_tlv(name, codestr, type, attr);
		return;
	}


	if (vendor) {
		radius_vendor_info_t* v;
		v = (radius_vendor_info_t *)g_hash_table_lookup(dict->vendors_by_name,vendor);

		if (! v) {
			g_string_append_printf(error, "Vendor: '%s', does not exist in %s:%i \n", vendor, fullpaths[include_stack_ptr], linenums[include_stack_ptr] );
			BEGIN JUNK;
			return;
		} else {
			by_id = v->attrs_by_id;
		}
	} else {
		by_id = dict->attrs_by_id;
	}

	code=strtol(codestr, NULL, 10);

	a=(radius_attr_info_t*)g_hash_table_lookup(by_id, GUINT_TO_POINTER(code));

	if (!a) {
		a = g_new(radius_attr_info_t,1);
		a->name = NULL;
		a->dissector = NULL;
	}

	a->code = code;
	a->encrypt = encrypted_flag;
	a->tagged =  tagged;
	a->type = type;
	a->vs = NULL;
	a->hf = -1;
	a->hf_alt = -1;
	a->hf_tag = -1;
	a->hf_len = -1;
	a->ett = -1;
	a->tlvs_by_id = NULL;

	if (a->name) {
		tmpName = a->name;
	}
	a->name = g_strdup(name);

	g_hash_table_insert(by_id, GUINT_TO_POINTER(code),a);
	g_hash_table_insert(dict->attrs_by_name,(gpointer) (a->name),a);

	/* Don't free the old name until after the hash_table ops, since it
	   seems to end up being used in there somewhere, causing valgrind
	   errors. https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=7803 */
	if (tmpName) {
		g_free((gpointer) tmpName);
	}
}

static void add_tlv(const gchar* name, const  gchar* codestr, radius_attr_dissector_t type, const gchar* attr) {
	radius_attr_info_t* a;
	radius_attr_info_t* s;
	guint32 code;

	a = (radius_attr_info_t*)g_hash_table_lookup(dict->attrs_by_name, attr);

	if (! a) {
		g_string_append_printf(error, "Attr: '%s', does not exist in %s:%i \n", attr, fullpaths[include_stack_ptr], linenums[include_stack_ptr]);
		BEGIN JUNK;
		return;
	}

	if (type == radius_tlv) {
		g_string_append_printf(error, "sub-TLV: '%s', sub-TLV's type is specified as tlv in %s:%i \n", name, fullpaths[include_stack_ptr], linenums[include_stack_ptr]);
		BEGIN JUNK;
		return;
	}


	if (! a->tlvs_by_id) {
		a->tlvs_by_id = g_hash_table_new(g_direct_hash,g_direct_equal);
	}

	code=strtol(codestr, NULL, 10);

	s = (radius_attr_info_t*)g_hash_table_lookup(a->tlvs_by_id, GUINT_TO_POINTER(code));

	if (!s) {
		s = g_new(radius_attr_info_t,1);
		s->name = NULL;
		s->dissector = NULL;
	}

	s->code = code;
	s->type = type;
	s->encrypt = FALSE;
	s->tagged = FALSE;
	s->dissector = NULL;
	s->vs = NULL;
	s->hf = -1;
	s->hf_alt = -1;
	s->hf_tag = -1;
	s->hf_len = -1;
	s->ett = -1;
	s->tlvs_by_id = NULL;

	if (s->name)
		g_free((gpointer) s->name);
	s->name = g_strdup(name);

	g_hash_table_insert(a->tlvs_by_id,GUINT_TO_POINTER(s->code),s);
	g_hash_table_insert(dict->tlvs_by_name,(gpointer) (s->name),s);
}

void add_value(const gchar* attrib_name, const gchar* repr, long value) {
	value_string v;
	GArray* a = (GArray*)g_hash_table_lookup(value_strings,attrib_name);

	if (! a) {
		a = g_array_new(TRUE,TRUE,sizeof(value_string));
		g_hash_table_insert(value_strings,g_strdup(attrib_name),a);
	}

	v.value = value;
	v.strptr = g_strdup(repr);

	g_array_append_val(a,v);
}

static void setup_tlvs(gpointer k _U_, gpointer v, gpointer p _U_) {
	radius_attr_info_t* s = (radius_attr_info_t*)v;
	gpointer key;

	union {
		GArray* a;
		gpointer p;
	} vs;

	if (g_hash_table_lookup_extended(value_strings, s->name, &key, &vs.p)) {
		s->vs = (value_string*)(void *)vs.a->data;
		g_array_free(vs.a, FALSE);
		g_hash_table_remove(value_strings, key);
		g_free(key);
	}
}

static void setup_attrs(gpointer k _U_, gpointer v, gpointer p _U_) {
	radius_attr_info_t* a = (radius_attr_info_t*)v;
	gpointer key;

	union {
		GArray* a;
		gpointer p;
	} vs;

	if (g_hash_table_lookup_extended(value_strings,a->name,&key,&vs.p) ) {
		a->vs = (value_string*)(void *)vs.a->data;
		g_array_free(vs.a,FALSE);
		g_hash_table_remove(value_strings,key);
		g_free(key);
	}

	if (a->tlvs_by_id) {
		g_hash_table_foreach(a->tlvs_by_id, setup_tlvs, p);
	}
}

static void setup_vendors(gpointer k _U_, gpointer v, gpointer p) {
	radius_vendor_info_t* vnd = (radius_vendor_info_t*)v;

	g_hash_table_foreach(vnd->attrs_by_id,setup_attrs,p);
}

static gboolean destroy_value_strings(gpointer k, gpointer v, gpointer p _U_) {
	value_string* vs = (value_string*)(void *)(((GArray*)v)->data);

	g_free(k);

	for (;vs->strptr;vs++) {
		g_free((void*)vs->strptr);
	}

	g_array_free((GArray*)v,TRUE);
	return TRUE;
}

gboolean radius_load_dictionary (radius_dictionary_t* d, gchar* dir, const gchar* filename, gchar** err_str) {
	int i;

	dict = d;
	directory = dir;

	fullpaths[include_stack_ptr] = g_strdup_printf("%s" G_DIR_SEPARATOR_S "%s",
	    directory,filename);

	error = g_string_new("");

	Radiusin = ws_fopen(fullpaths[include_stack_ptr],"r");

	if (!Radiusin) {
		g_string_append_printf(error, "Could not open file: '%s', error: %s\n", fullpaths[include_stack_ptr], g_strerror(errno) );
		g_free(fullpaths[include_stack_ptr]);
		*err_str = error->str;
		g_string_free(error,FALSE);
		return FALSE;
	}

	value_strings = g_hash_table_new(g_str_hash,g_str_equal);

	BEGIN WS_OUT;

	Radiuslex();

	if (Radiusin != NULL) fclose(Radiusin);
	Radiusin = NULL;

	for (i=0; i < 10; i++) {
		if (fullpaths[i]) g_free(fullpaths[i]);
	}

	g_hash_table_foreach(dict->attrs_by_id,setup_attrs,NULL);
	g_hash_table_foreach(dict->vendors_by_id,setup_vendors,NULL);
	g_hash_table_foreach_remove(value_strings,destroy_value_strings,NULL);

	if (error->len > 0) {
		*err_str = error->str;
		g_string_free(error,FALSE);
		return FALSE;
	} else {
		*err_str = NULL;
		g_string_free(error,TRUE);
		return TRUE;
	}
}

/*
 * We want to stop processing when we get to the end of the input.
 * (%option noyywrap is not used because if used then
 * some flex versions (eg: 2.5.35) generate code which causes
 * warnings by the Windows VC compiler).
 */

int Radiuswrap(void) {
    return 1;
}

/*
 * Editor modelines  -  http://www.wireshark.org/tools/modelines.html
 *
 * Local variables:
 * c-basic-offset: 8
 * tab-width: 8
 * indent-tabs-mode: t
 * End:
 *
 * vi: set shiftwidth=8 tabstop=8 noexpandtab:
 * :indentSize=8:tabSize=8:noTabs=false:
 */

