#!/bin/bash

#
# app
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#             Eduard Grasa <e DOT grasa AT i2cat DOT net>
#

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/irati/lib java -jar /usr/local/irati/share/rinad/ipcprocess/rina.ipcprocess.impl-1.0.0-irati-SNAPSHOT.jar $1 $2 $3 $4
