#!/bin/bash

#
# ipcmd
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#             Eduard Grasa <e DOT grasa AT i2cat DOT net>
#

me="ipcmd"

LP=/home/irati/test_dir/lib

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LP java -jar /home/irati/test_dir/share/java/ipcmd.jar
