// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DirectoryForwardingTableEntryArrayMessage.proto

#ifndef PROTOBUF_DirectoryForwardingTableEntryArrayMessage_2eproto__INCLUDED
#define PROTOBUF_DirectoryForwardingTableEntryArrayMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "DirectoryForwardingTableEntryMessage.pb.h"
// @@protoc_insertion_point(includes)

namespace rina {
namespace messages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DirectoryForwardingTableEntryArrayMessage_2eproto();
void protobuf_AssignDesc_DirectoryForwardingTableEntryArrayMessage_2eproto();
void protobuf_ShutdownFile_DirectoryForwardingTableEntryArrayMessage_2eproto();

class directoryForwardingTableEntrySet_t;

// ===================================================================

class directoryForwardingTableEntrySet_t : public ::google::protobuf::Message {
 public:
  directoryForwardingTableEntrySet_t();
  virtual ~directoryForwardingTableEntrySet_t();

  directoryForwardingTableEntrySet_t(const directoryForwardingTableEntrySet_t& from);

  inline directoryForwardingTableEntrySet_t& operator=(const directoryForwardingTableEntrySet_t& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const directoryForwardingTableEntrySet_t& default_instance();

  void Swap(directoryForwardingTableEntrySet_t* other);

  // implements Message ----------------------------------------------

  directoryForwardingTableEntrySet_t* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const directoryForwardingTableEntrySet_t& from);
  void MergeFrom(const directoryForwardingTableEntrySet_t& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .rina.messages.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
  inline int directoryforwardingtableentry_size() const;
  inline void clear_directoryforwardingtableentry();
  static const int kDirectoryForwardingTableEntryFieldNumber = 1;
  inline const ::rina::messages::directoryForwardingTableEntry_t& directoryforwardingtableentry(int index) const;
  inline ::rina::messages::directoryForwardingTableEntry_t* mutable_directoryforwardingtableentry(int index);
  inline ::rina::messages::directoryForwardingTableEntry_t* add_directoryforwardingtableentry();
  inline const ::google::protobuf::RepeatedPtrField< ::rina::messages::directoryForwardingTableEntry_t >&
      directoryforwardingtableentry() const;
  inline ::google::protobuf::RepeatedPtrField< ::rina::messages::directoryForwardingTableEntry_t >*
      mutable_directoryforwardingtableentry();

  // @@protoc_insertion_point(class_scope:rina.messages.directoryForwardingTableEntrySet_t)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::rina::messages::directoryForwardingTableEntry_t > directoryforwardingtableentry_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_DirectoryForwardingTableEntryArrayMessage_2eproto();
  friend void protobuf_AssignDesc_DirectoryForwardingTableEntryArrayMessage_2eproto();
  friend void protobuf_ShutdownFile_DirectoryForwardingTableEntryArrayMessage_2eproto();

  void InitAsDefaultInstance();
  static directoryForwardingTableEntrySet_t* default_instance_;
};
// ===================================================================


// ===================================================================

// directoryForwardingTableEntrySet_t

// repeated .rina.messages.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
inline int directoryForwardingTableEntrySet_t::directoryforwardingtableentry_size() const {
  return directoryforwardingtableentry_.size();
}
inline void directoryForwardingTableEntrySet_t::clear_directoryforwardingtableentry() {
  directoryforwardingtableentry_.Clear();
}
inline const ::rina::messages::directoryForwardingTableEntry_t& directoryForwardingTableEntrySet_t::directoryforwardingtableentry(int index) const {
  return directoryforwardingtableentry_.Get(index);
}
inline ::rina::messages::directoryForwardingTableEntry_t* directoryForwardingTableEntrySet_t::mutable_directoryforwardingtableentry(int index) {
  return directoryforwardingtableentry_.Mutable(index);
}
inline ::rina::messages::directoryForwardingTableEntry_t* directoryForwardingTableEntrySet_t::add_directoryforwardingtableentry() {
  return directoryforwardingtableentry_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::rina::messages::directoryForwardingTableEntry_t >&
directoryForwardingTableEntrySet_t::directoryforwardingtableentry() const {
  return directoryforwardingtableentry_;
}
inline ::google::protobuf::RepeatedPtrField< ::rina::messages::directoryForwardingTableEntry_t >*
directoryForwardingTableEntrySet_t::mutable_directoryforwardingtableentry() {
  return &directoryforwardingtableentry_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace rina

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DirectoryForwardingTableEntryArrayMessage_2eproto__INCLUDED
