// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NeighborArrayMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "NeighborArrayMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace rina {
namespace messages {

namespace {

const ::google::protobuf::Descriptor* neighbors_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  neighbors_t_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_NeighborArrayMessage_2eproto() {
  protobuf_AddDesc_NeighborArrayMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "NeighborArrayMessage.proto");
  GOOGLE_CHECK(file != NULL);
  neighbors_t_descriptor_ = file->message_type(0);
  static const int neighbors_t_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(neighbors_t, neighbor_),
  };
  neighbors_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      neighbors_t_descriptor_,
      neighbors_t::default_instance_,
      neighbors_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(neighbors_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(neighbors_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(neighbors_t));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_NeighborArrayMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    neighbors_t_descriptor_, &neighbors_t::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_NeighborArrayMessage_2eproto() {
  delete neighbors_t::default_instance_;
  delete neighbors_t_reflection_;
}

void protobuf_AddDesc_NeighborArrayMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::rina::messages::protobuf_AddDesc_NeighborMessage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032NeighborArrayMessage.proto\022\rrina.messa"
    "ges\032\025NeighborMessage.proto\":\n\013neighbors_"
    "t\022+\n\010neighbor\030\001 \003(\0132\031.rina.messages.neig"
    "hbor_tB,\n*rina.encoding.impl.googleproto"
    "buf.neighbor", 172);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NeighborArrayMessage.proto", &protobuf_RegisterTypes);
  neighbors_t::default_instance_ = new neighbors_t();
  neighbors_t::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_NeighborArrayMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_NeighborArrayMessage_2eproto {
  StaticDescriptorInitializer_NeighborArrayMessage_2eproto() {
    protobuf_AddDesc_NeighborArrayMessage_2eproto();
  }
} static_descriptor_initializer_NeighborArrayMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int neighbors_t::kNeighborFieldNumber;
#endif  // !_MSC_VER

neighbors_t::neighbors_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void neighbors_t::InitAsDefaultInstance() {
}

neighbors_t::neighbors_t(const neighbors_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void neighbors_t::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

neighbors_t::~neighbors_t() {
  SharedDtor();
}

void neighbors_t::SharedDtor() {
  if (this != default_instance_) {
  }
}

void neighbors_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* neighbors_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return neighbors_t_descriptor_;
}

const neighbors_t& neighbors_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_NeighborArrayMessage_2eproto();
  return *default_instance_;
}

neighbors_t* neighbors_t::default_instance_ = NULL;

neighbors_t* neighbors_t::New() const {
  return new neighbors_t;
}

void neighbors_t::Clear() {
  neighbor_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool neighbors_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .rina.messages.neighbor_t neighbor = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_neighbor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_neighbor()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_neighbor;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void neighbors_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .rina.messages.neighbor_t neighbor = 1;
  for (int i = 0; i < this->neighbor_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->neighbor(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* neighbors_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .rina.messages.neighbor_t neighbor = 1;
  for (int i = 0; i < this->neighbor_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->neighbor(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int neighbors_t::ByteSize() const {
  int total_size = 0;

  // repeated .rina.messages.neighbor_t neighbor = 1;
  total_size += 1 * this->neighbor_size();
  for (int i = 0; i < this->neighbor_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->neighbor(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void neighbors_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const neighbors_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const neighbors_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void neighbors_t::MergeFrom(const neighbors_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  neighbor_.MergeFrom(from.neighbor_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void neighbors_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void neighbors_t::CopyFrom(const neighbors_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool neighbors_t::IsInitialized() const {

  return true;
}

void neighbors_t::Swap(neighbors_t* other) {
  if (other != this) {
    neighbor_.Swap(&other->neighbor_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata neighbors_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = neighbors_t_descriptor_;
  metadata.reflection = neighbors_t_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace rina

// @@protoc_insertion_point(global_scope)
