// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofiles/NeighborMessage.proto

package rina.encoding.impl.googleprotobuf.neighbor;

public final class NeighborMessage {
  private NeighborMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class neighbor_t extends
      com.google.protobuf.GeneratedMessage {
    // Use neighbor_t.newBuilder() to construct.
    private neighbor_t() {
      initFields();
    }
    private neighbor_t(boolean noInit) {}
    
    private static final neighbor_t defaultInstance;
    public static neighbor_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public neighbor_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.internal_static_rina_messages_neighbor_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.internal_static_rina_messages_neighbor_t_fieldAccessorTable;
    }
    
    // optional string applicationProcessName = 1;
    public static final int APPLICATIONPROCESSNAME_FIELD_NUMBER = 1;
    private boolean hasApplicationProcessName;
    private java.lang.String applicationProcessName_ = "";
    public boolean hasApplicationProcessName() { return hasApplicationProcessName; }
    public java.lang.String getApplicationProcessName() { return applicationProcessName_; }
    
    // optional string applicationProcessInstance = 2;
    public static final int APPLICATIONPROCESSINSTANCE_FIELD_NUMBER = 2;
    private boolean hasApplicationProcessInstance;
    private java.lang.String applicationProcessInstance_ = "";
    public boolean hasApplicationProcessInstance() { return hasApplicationProcessInstance; }
    public java.lang.String getApplicationProcessInstance() { return applicationProcessInstance_; }
    
    // optional uint64 address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private boolean hasAddress;
    private long address_ = 0L;
    public boolean hasAddress() { return hasAddress; }
    public long getAddress() { return address_; }
    
    // repeated string supportingDifs = 4;
    public static final int SUPPORTINGDIFS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.String> supportingDifs_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getSupportingDifsList() {
      return supportingDifs_;
    }
    public int getSupportingDifsCount() { return supportingDifs_.size(); }
    public java.lang.String getSupportingDifs(int index) {
      return supportingDifs_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasApplicationProcessName()) {
        output.writeString(1, getApplicationProcessName());
      }
      if (hasApplicationProcessInstance()) {
        output.writeString(2, getApplicationProcessInstance());
      }
      if (hasAddress()) {
        output.writeUInt64(3, getAddress());
      }
      for (java.lang.String element : getSupportingDifsList()) {
        output.writeString(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasApplicationProcessName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getApplicationProcessName());
      }
      if (hasApplicationProcessInstance()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getApplicationProcessInstance());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getAddress());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getSupportingDifsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getSupportingDifsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t result;
      
      // Construct using rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t();
        return builder;
      }
      
      protected rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t.getDescriptor();
      }
      
      public rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t getDefaultInstanceForType() {
        return rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.supportingDifs_ != java.util.Collections.EMPTY_LIST) {
          result.supportingDifs_ =
            java.util.Collections.unmodifiableList(result.supportingDifs_);
        }
        rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t) {
          return mergeFrom((rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t other) {
        if (other == rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t.getDefaultInstance()) return this;
        if (other.hasApplicationProcessName()) {
          setApplicationProcessName(other.getApplicationProcessName());
        }
        if (other.hasApplicationProcessInstance()) {
          setApplicationProcessInstance(other.getApplicationProcessInstance());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (!other.supportingDifs_.isEmpty()) {
          if (result.supportingDifs_.isEmpty()) {
            result.supportingDifs_ = new java.util.ArrayList<java.lang.String>();
          }
          result.supportingDifs_.addAll(other.supportingDifs_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setApplicationProcessName(input.readString());
              break;
            }
            case 18: {
              setApplicationProcessInstance(input.readString());
              break;
            }
            case 24: {
              setAddress(input.readUInt64());
              break;
            }
            case 34: {
              addSupportingDifs(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string applicationProcessName = 1;
      public boolean hasApplicationProcessName() {
        return result.hasApplicationProcessName();
      }
      public java.lang.String getApplicationProcessName() {
        return result.getApplicationProcessName();
      }
      public Builder setApplicationProcessName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasApplicationProcessName = true;
        result.applicationProcessName_ = value;
        return this;
      }
      public Builder clearApplicationProcessName() {
        result.hasApplicationProcessName = false;
        result.applicationProcessName_ = getDefaultInstance().getApplicationProcessName();
        return this;
      }
      
      // optional string applicationProcessInstance = 2;
      public boolean hasApplicationProcessInstance() {
        return result.hasApplicationProcessInstance();
      }
      public java.lang.String getApplicationProcessInstance() {
        return result.getApplicationProcessInstance();
      }
      public Builder setApplicationProcessInstance(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasApplicationProcessInstance = true;
        result.applicationProcessInstance_ = value;
        return this;
      }
      public Builder clearApplicationProcessInstance() {
        result.hasApplicationProcessInstance = false;
        result.applicationProcessInstance_ = getDefaultInstance().getApplicationProcessInstance();
        return this;
      }
      
      // optional uint64 address = 3;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public long getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(long value) {
        result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = 0L;
        return this;
      }
      
      // repeated string supportingDifs = 4;
      public java.util.List<java.lang.String> getSupportingDifsList() {
        return java.util.Collections.unmodifiableList(result.supportingDifs_);
      }
      public int getSupportingDifsCount() {
        return result.getSupportingDifsCount();
      }
      public java.lang.String getSupportingDifs(int index) {
        return result.getSupportingDifs(index);
      }
      public Builder setSupportingDifs(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.supportingDifs_.set(index, value);
        return this;
      }
      public Builder addSupportingDifs(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.supportingDifs_.isEmpty()) {
          result.supportingDifs_ = new java.util.ArrayList<java.lang.String>();
        }
        result.supportingDifs_.add(value);
        return this;
      }
      public Builder addAllSupportingDifs(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.supportingDifs_.isEmpty()) {
          result.supportingDifs_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.supportingDifs_);
        return this;
      }
      public Builder clearSupportingDifs() {
        result.supportingDifs_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.neighbor_t)
    }
    
    static {
      defaultInstance = new neighbor_t(true);
      rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.neighbor_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_neighbor_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_neighbor_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n protofiles/NeighborMessage.proto\022\rrina" +
      ".messages\"y\n\nneighbor_t\022\036\n\026applicationPr" +
      "ocessName\030\001 \001(\t\022\"\n\032applicationProcessIns" +
      "tance\030\002 \001(\t\022\017\n\007address\030\003 \001(\004\022\026\n\016supporti" +
      "ngDifs\030\004 \003(\tB,\n*rina.encoding.impl.googl" +
      "eprotobuf.neighbor"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_neighbor_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_neighbor_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_neighbor_t_descriptor,
              new java.lang.String[] { "ApplicationProcessName", "ApplicationProcessInstance", "Address", "SupportingDifs", },
              rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t.class,
              rina.encoding.impl.googleprotobuf.neighbor.NeighborMessage.neighbor_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
