#!/bin/sh
# -*- sh -*-

#
# install
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=build

echo "${ME}: Installing librina ..."
(cd librina && make install) || {
    echo "${ME}: Cannot install librina"
    exit 1
}

echo "${ME}: Installation completed successfully"
