// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofiles/DirectoryForwardingTableEntryArrayMessage.proto

package rina.encoding.impl.googleprotobuf.directoryforwardingtable;

public final class DirectoryForwardingTableEntryArrayMessage {
  private DirectoryForwardingTableEntryArrayMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class directoryForwardingTableEntrySet_t extends
      com.google.protobuf.GeneratedMessage {
    // Use directoryForwardingTableEntrySet_t.newBuilder() to construct.
    private directoryForwardingTableEntrySet_t() {
      initFields();
    }
    private directoryForwardingTableEntrySet_t(boolean noInit) {}
    
    private static final directoryForwardingTableEntrySet_t defaultInstance;
    public static directoryForwardingTableEntrySet_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public directoryForwardingTableEntrySet_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.internal_static_rina_messages_directoryForwardingTableEntrySet_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.internal_static_rina_messages_directoryForwardingTableEntrySet_t_fieldAccessorTable;
    }
    
    // repeated .rina.messages.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
    public static final int DIRECTORYFORWARDINGTABLEENTRY_FIELD_NUMBER = 1;
    private java.util.List<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t> directoryForwardingTableEntry_ =
      java.util.Collections.emptyList();
    public java.util.List<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t> getDirectoryForwardingTableEntryList() {
      return directoryForwardingTableEntry_;
    }
    public int getDirectoryForwardingTableEntryCount() { return directoryForwardingTableEntry_.size(); }
    public rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t getDirectoryForwardingTableEntry(int index) {
      return directoryForwardingTableEntry_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t element : getDirectoryForwardingTableEntryList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t element : getDirectoryForwardingTableEntryList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t element : getDirectoryForwardingTableEntryList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t result;
      
      // Construct using rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t();
        return builder;
      }
      
      protected rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t.getDescriptor();
      }
      
      public rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t getDefaultInstanceForType() {
        return rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.directoryForwardingTableEntry_ != java.util.Collections.EMPTY_LIST) {
          result.directoryForwardingTableEntry_ =
            java.util.Collections.unmodifiableList(result.directoryForwardingTableEntry_);
        }
        rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t) {
          return mergeFrom((rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t other) {
        if (other == rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t.getDefaultInstance()) return this;
        if (!other.directoryForwardingTableEntry_.isEmpty()) {
          if (result.directoryForwardingTableEntry_.isEmpty()) {
            result.directoryForwardingTableEntry_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t>();
          }
          result.directoryForwardingTableEntry_.addAll(other.directoryForwardingTableEntry_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDirectoryForwardingTableEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .rina.messages.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
      public java.util.List<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t> getDirectoryForwardingTableEntryList() {
        return java.util.Collections.unmodifiableList(result.directoryForwardingTableEntry_);
      }
      public int getDirectoryForwardingTableEntryCount() {
        return result.getDirectoryForwardingTableEntryCount();
      }
      public rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t getDirectoryForwardingTableEntry(int index) {
        return result.getDirectoryForwardingTableEntry(index);
      }
      public Builder setDirectoryForwardingTableEntry(int index, rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.directoryForwardingTableEntry_.set(index, value);
        return this;
      }
      public Builder setDirectoryForwardingTableEntry(int index, rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t.Builder builderForValue) {
        result.directoryForwardingTableEntry_.set(index, builderForValue.build());
        return this;
      }
      public Builder addDirectoryForwardingTableEntry(rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.directoryForwardingTableEntry_.isEmpty()) {
          result.directoryForwardingTableEntry_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t>();
        }
        result.directoryForwardingTableEntry_.add(value);
        return this;
      }
      public Builder addDirectoryForwardingTableEntry(rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t.Builder builderForValue) {
        if (result.directoryForwardingTableEntry_.isEmpty()) {
          result.directoryForwardingTableEntry_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t>();
        }
        result.directoryForwardingTableEntry_.add(builderForValue.build());
        return this;
      }
      public Builder addAllDirectoryForwardingTableEntry(
          java.lang.Iterable<? extends rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t> values) {
        if (result.directoryForwardingTableEntry_.isEmpty()) {
          result.directoryForwardingTableEntry_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.directoryForwardingTableEntry_t>();
        }
        super.addAll(values, result.directoryForwardingTableEntry_);
        return this;
      }
      public Builder clearDirectoryForwardingTableEntry() {
        result.directoryForwardingTableEntry_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.directoryForwardingTableEntrySet_t)
    }
    
    static {
      defaultInstance = new directoryForwardingTableEntrySet_t(true);
      rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.directoryForwardingTableEntrySet_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_directoryForwardingTableEntrySet_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_directoryForwardingTableEntrySet_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:protofiles/DirectoryForwardingTableEnt" +
      "ryArrayMessage.proto\022\rrina.messages\0325pro" +
      "tofiles/DirectoryForwardingTableEntryMes" +
      "sage.proto\"{\n\"directoryForwardingTableEn" +
      "trySet_t\022U\n\035directoryForwardingTableEntr" +
      "y\030\001 \003(\0132..rina.messages.directoryForward" +
      "ingTableEntry_tB<\n:rina.encoding.impl.go" +
      "ogleprotobuf.directoryforwardingtable"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_directoryForwardingTableEntrySet_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_directoryForwardingTableEntrySet_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_directoryForwardingTableEntrySet_t_descriptor,
              new java.lang.String[] { "DirectoryForwardingTableEntry", },
              rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t.class,
              rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryArrayMessage.directoryForwardingTableEntrySet_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rina.encoding.impl.googleprotobuf.directoryforwardingtable.DirectoryForwardingTableEntryMessage.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
