#!/bin/bash -e

export INSTALL_PREFIX=~/install
export PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig
export LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
export VERSION=1.2.0

# Install version 2.6.1 of Protocol Buffers
wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
tar -xvzf protobuf-2.6.1.tar.gz
pushd protobuf-2.6.1
./configure && make
sudo make install
popd
sudo ldconfig

# Run the IRATI stack build script
mkdir build
mkdir -p $INSTALL_PREFIX
./configure --prefix $INSTALL_PREFIX
sudo make install
cd build/librina
make check-functional
cd ../..
cd build/rinad
sudo make check
