#!/bin/sh

# A script to build and install the IRATI kernel on Archlinux systems
# See https://wiki.archlinux.org/index.php/Kernels/Traditional_compilation

set -x
make headers_check
make -j8 || exit 1
sudo make modules_install
sudo cp -v arch/x86/boot/bzImage /boot/vmlinuz-irati
sudo mkinitcpio -k $(make kernelrelease) -g /boot/initramfs-irati.img
