#!/bin/sh
# -*- sh -*-

#
# build
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=build

echo "${ME}: Building librina ..."
(cd librina && make) || {
    echo "${ME}: Cannot build librina"
    exit 1
}

echo "${ME}: Build completed successfully"
