#!/bin/sh
# -*- sh -*-

#
# uninstall
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

ME=build

echo "${ME}: Uninstalling librina ..."
(cd librina && make) || {
    echo "${ME}: Cannot uninstall librina"
    exit 1
}

echo "${ME}: Uninstallation completed successfully"
